import * as contactInvitationIdentification from "./contactInvitationIdentification";

test("contactInvitationIdentification.stringify", () => {
  expect(
    contactInvitationIdentification.stringify({
      version: "1",
      userId: "8d2f9d7b-ada3-4331-aa15-3c052d40c45e",
      userSigningKey: "1234567hgfda",
      serverSecret: "123123",
      clientSecret: "321321",
    })
  ).toBe(
    "clientSecret=321321&serverSecret=123123&userId=8d2f9d7b-ada3-4331-aa15-3c052d40c45e&userSigningKey=1234567hgfda&version=1"
  );
});

test("contactInvitationIdentification.parse", () => {
  expect(
    contactInvitationIdentification.parse(
      "clientSecret=321321&serverSecret=123123&userId=8d2f9d7b-ada3-4331-aa15-3c052d40c45e&userSigningKey=1234567hgfda&version=1"
    )
  ).toMatchObject({
    version: "1",
    userId: "8d2f9d7b-ada3-4331-aa15-3c052d40c45e",
    userSigningKey: "1234567hgfda",
    serverSecret: "123123",
    clientSecret: "321321",
  });
});

test("contactInvitationIdentification.parse fails due wrong version", () => {
  expect(() =>
    contactInvitationIdentification.parse(
      "clientSecret=321321&serverSecret=123123&userId=8d2f9d7b-ada3-4331-aa15-3c052d40c45e&userSigningKey=1234567hgfda&version=44"
    )
  ).toThrow("The invitation was generated by a newer App version.");
});

test("contactInvitationIdentification.parse fails due missing entry", () => {
  expect(() =>
    contactInvitationIdentification.parse(
      "clientSecret=321321&serverSecret=123123&userId=8d2f9d7b-ada3-4331-aa15-3c052d40c45e&userSigningKey=1234567hgfda"
    )
  ).toThrow("Missing the version entry in the contact identification.");
  expect(() =>
    contactInvitationIdentification.parse(
      "clientSecret=321321&serverSecret=123123&userSigningKey=1234567hgfda&version=1"
    )
  ).toThrow("Missing the userId entry in the contact identification.");
  expect(() =>
    contactInvitationIdentification.parse(
      "serverSecret=123123&userId=8d2f9d7b-ada3-4331-aa15-3c052d40c45e&userSigningKey=1234567hgfda&version=1"
    )
  ).toThrow("Missing the clientSecret entry in the contact identification.");
  expect(() =>
    contactInvitationIdentification.parse(
      "clientSecret=321321&userId=8d2f9d7b-ada3-4331-aa15-3c052d40c45e&userSigningKey=1234567hgfda&version=1"
    )
  ).toThrow("Missing the serverSecret entry in the contact identification.");
  expect(() =>
    contactInvitationIdentification.parse(
      "clientSecret=321321&serverSecret=123123&userId=8d2f9d7b-ada3-4331-aa15-3c052d40c45e&version=1"
    )
  ).toThrow("Missing the userSigningKey entry in the contact identification.");
});
