import queryString from "query-string";

export type ContactInviation = {
  version: "1";
  userId: string;
  userSigningKey: string;
  serverSecret: string;
  clientSecret: string;
};

export function parse(value: string): ContactInviation {
  const result = queryString.parse(value);
  if (typeof result.version !== "string") {
    throw new Error("Missing the version entry in the contact identification.");
  }
  if (result.version !== "1") {
    throw new Error("The invitation was generated by a newer App version.");
  }
  if (typeof result.userId !== "string") {
    throw new Error("Missing the userId entry in the contact identification.");
  }
  if (typeof result.userSigningKey !== "string") {
    throw new Error(
      "Missing the userSigningKey entry in the contact identification."
    );
  }
  if (typeof result.serverSecret !== "string") {
    throw new Error(
      "Missing the serverSecret entry in the contact identification."
    );
  }
  if (typeof result.clientSecret !== "string") {
    throw new Error(
      "Missing the clientSecret entry in the contact identification."
    );
  }
  return {
    version: "1",
    userId: result.userId,
    userSigningKey: result.userSigningKey,
    serverSecret: result.serverSecret,
    clientSecret: result.clientSecret,
  };
}

export function stringify(contactInviation: ContactInviation) {
  return queryString.stringify(contactInviation);
}
